### PR TITLE
Initial implementation of the table extension

### PR DESCRIPTION
**Pull request by madc**
This PR introduces a first draft of the table extension based on https://github.com/formfcw/directus-extension-flexible-editor/discussions/27

Status:
- [x] Enable tool vie interface settings
- [x] Paste table into editor
- [ ] Add useful menu item to editor tools (dropdown?)

I'm open for suggestions and support on how to integrate the tool menu into the editor.

### CODE REVIEW

**Review by formfcw — COMMENTED** [review]
I am delighted to welcome you as the first contributor to Flexible Editor.

I have checked your code and so far it fits very well. I then [changed the icon](https://github.com/formfcw/directus-extension-flexible-editor/pull/32/commits/aca8090b527a40ce083f05c3d9a061fd49c09c43) and [added basic table styles](https://github.com/formfcw/directus-extension-flexible-editor/pull/32/commits/43eff0612af8774ca407204ad80988e0113fe63c) to visualize the table in the editor. I also refactored some code to give you a convenient way to add all table actions to a submenu. [Take a look at the commit](https://github.com/formfcw/directus-extension-flexible-editor/pull/32/commits/93872fa3a5879d8ff284f1cde2a397944b9e28d3), which should show you how to continue adding all the table commands from Tiptap. You may also want to take a look at the [Directus Components](https://components.directus.io) and especially the `VListGroup` component, as it may come in handy.

Thank you!


changes

**Comment by madc** [comment]
Thanks for taking the time and reviewing/extending my PR!

Following your lead, I just added some of the actions:
image

I tried to keep it as useful and minimal as possible. Let me know, if that's OK.
There is still room for improvement (i.e. icons), but I think this is a working implementation so far.

**Review by formfcw — APPROVED** [review]
@madc Thanks for your contribution. I've just added a few final touches.

tables

I think it's perfect now and we don't need any more features. What do you think?

**Comment by madc** [comment]
One small addition: I've been looking through some other implementations of tables in WYSIWYG editors and they all seem to use the singular terms (cell, column, row).

**Pull request merged**
